=== androsovgr/document-reporter/document-reporter-parent/config/doc-template/template.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="template">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="attribute" maxOccurs="unbounded"
					minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="parameters" minOccurs="0" nillable="false">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="parameter" maxOccurs="unbounded"
											minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="key" />
													<xs:element type="xs:string" name="value" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="validators" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="validator" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="parameters">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="parameter" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:string" name="key" />
																			<xs:element type="xs:string" name="value" />
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute type="xs:string" name="validatorClass"
													use="required" />
												<xs:attribute type="xs:string" name="validatorMessage"
													use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="key" use="optional" />
						<xs:attribute type="xs:string" name="label" use="optional" />
						<xs:attribute type="xs:string" name="retrieverClass"
							use="optional" />
						<xs:attribute type="xs:boolean" name="silence" use="optional"
							default="false" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== androsovgr/document-reporter/document-reporter-parent/config/doc-template/history.xml
<?xml version="1.0" encoding="UTF-8" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="template.xsd">
	<attribute key="tittle" label="Название реферата"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameters>
			<parameter>
				<key>expression</key>
				<value>(.*)</value>
			</parameter>
			<parameter>
				<key>table-position</key>
				<value>first</value>
			</parameter>
			<parameter>
				<key>row-number</key>
				<value>2</value>
			</parameter>
			<parameter>
				<key>column-number</key>
				<value>1</value>
			</parameter>
		</parameters>
	</attribute>
	<attribute key="subject" label="Предмет"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever"
		silence="true">
		<parameters>
			<parameter>
				<key>expression</key>
				<value>Реферат по (.*) аспиранта кафедры.*</value>
			</parameter>
			<parameter>
				<key>table-position</key>
				<value>first</value>
			</parameter>
			<parameter>
				<key>row-number</key>
				<value>3</value>
			</parameter>
			<parameter>
				<key>column-number</key>
				<value>1</value>
			</parameter>
			<parameter>
				<key>line</key>
				<value>2</value>
			</parameter>
		</parameters>
		<validators>
			<validator validatorClass="ru.mephi.dr.parser.validator.ValueLikeValdator"
				validatorMessage="Тема реферата неправильная">
				<parameters>
					<parameter>
						<key>regexp</key>
						<value>истори.? наук.?</value>
					</parameter>
				</parameters>
			</validator>
		</validators>
	</attribute>
	<attribute key="department" label="Кафедра"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameters>
			<parameter>
				<key>expression</key>
				<value>.*кафедры №?(.*)</value>
			</parameter>
			<parameter>
				<key>table-position</key>
				<value>first</value>
			</parameter>
			<parameter>
				<key>row-number</key>
				<value>3</value>
			</parameter>
			<parameter>
				<key>column-number</key>
				<value>1</value>
			</parameter>
			<parameter>
				<key>line</key>
				<value>2</value>
			</parameter>
		</parameters>
	</attribute>
	<attribute key="name" label="Имя аспиранта"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameters>
			<parameter>
				<key>expression</key>
				<value>Выполнил: (.*)</value>
			</parameter>
			<parameter>
				<key>table-position</key>
				<value>first</value>
			</parameter>
			<parameter>
				<key>row-number</key>
				<value>3</value>
			</parameter>
			<parameter>
				<key>column-number</key>
				<value>1</value>
			</parameter>
			<parameter>
				<key>line</key>
				<value>3</value>
			</parameter>
		</parameters>
	</attribute>
	<attribute key="specialty" label="Специальность аспиранта"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameters>
			<parameter>
				<key>expression</key>
				<value>(С|с).*(\d\d\.\d\d\.\d\d)</value>
			</parameter>
			<parameter>
				<key>expression-group-number</key>
				<value>2</value>
			</parameter>
			<parameter>
				<key>table-position</key>
				<value>first</value>
			</parameter>
			<parameter>
				<key>row-number</key>
				<value>3</value>
			</parameter>
			<parameter>
				<key>column-number</key>
				<value>1</value>
			</parameter>
			<parameter>
				<key>line</key>
				<value>4</value>
			</parameter>
		</parameters>
	</attribute>
	<attribute key="pageCount" label="Количество страниц"
		retrieverClass="ru.mephi.dr.parser.retriever.PageCountRetriever" />
</template>

=== androsovgr/document-reporter/document-reporter-parent/document-reporter-parser/src/test/resources/input/template/history.xml
<?xml version="1.0" encoding="UTF-8" ?>
<template xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="template.xsd">
	<attribute key="tittle" label="Название реферата"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameter>
			<key>expression</key>
			<value>(.*)</value>
		</parameter>
		<parameter>
			<key>table-position</key>
			<value>first</value>
		</parameter>
		<parameter>
			<key>row-number</key>
			<value>2</value>
		</parameter>
		<parameter>
			<key>column-number</key>
			<value>1</value>
		</parameter>
	</attribute>
	<attribute key="subject" label="Предмет"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameter>
			<key>expression</key>
			<value>Реферат по (.*) аспиранта кафедры.*</value>
		</parameter>
		<parameter>
			<key>table-position</key>
			<value>first</value>
		</parameter>
		<parameter>
			<key>row-number</key>
			<value>3</value>
		</parameter>
		<parameter>
			<key>column-number</key>
			<value>1</value>
		</parameter>
		<parameter>
			<key>line</key>
			<value>2</value>
		</parameter>
	</attribute>
	<attribute key="department" label="Кафедра"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameter>
			<key>expression</key>
			<value>.*кафедры №?(.*)</value>
		</parameter>
		<parameter>
			<key>table-position</key>
			<value>first</value>
		</parameter>
		<parameter>
			<key>row-number</key>
			<value>3</value>
		</parameter>
		<parameter>
			<key>column-number</key>
			<value>1</value>
		</parameter>
		<parameter>
			<key>line</key>
			<value>2</value>
		</parameter>
	</attribute>
	<attribute key="name" label="Имя аспиранта"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameter>
			<key>expression</key>
			<value>(.*)</value>
		</parameter>
		<parameter>
			<key>table-position</key>
			<value>first</value>
		</parameter>
		<parameter>
			<key>row-number</key>
			<value>3</value>
		</parameter>
		<parameter>
			<key>column-number</key>
			<value>1</value>
		</parameter>
		<parameter>
			<key>line</key>
			<value>3</value>
		</parameter>
	</attribute>
	<attribute key="specialty" label="Специальность аспиранта"
		retrieverClass="ru.mephi.dr.parser.retriever.CellValueRetriever">
		<parameter>
			<key>expression</key>
			<value>(С|с).*(\d\d\.\d\d\.\d\d)</value>
		</parameter>
		<parameter>
			<key>expression-group-number</key>
			<value>2</value>
		</parameter>
		<parameter>
			<key>table-position</key>
			<value>first</value>
		</parameter>
		<parameter>
			<key>row-number</key>
			<value>3</value>
		</parameter>
		<parameter>
			<key>column-number</key>
			<value>1</value>
		</parameter>
		<parameter>
			<key>line</key>
			<value>4</value>
		</parameter>
	</attribute>
	<attribute key="pageCount" label="Количество страниц"
		retrieverClass="ru.mephi.dr.parser.retriever.PageCountRetriever" />
</template>
